### ISSUE TITLE
Unhandled promise rejection Error: Error invoking FetchConfig. Check the inner error for details.

### ISSUE THREAD

**Issue by ghost** [doktordirk/aurelia-auth-loopback-sample#2]
spinning up the system throws; 
"Unhandled promise rejection Error: Error invoking FetchConfig. Check the inner error for details."
same thing happens when using paul van bale's aurelia-auth with the suggested fix being to replace;
import {FetchConfig} from 'aurelia-auth';
with
import FetchConfig from 'aurelia-auth/app.fetch-httpClient.config';
in client/src/app.js
however replacing
import {FetchConfig} from 'spoonx/aurelia-auth';
with
import FetchConfig from 'spoonx/aurelia-auth/app.fetch-httpClient.config';
doesn't fix the issue.

**Comment by asdac** [comment]
Full stack trace;

Unhandled promise rejection Error: Error invoking FetchConfig. Check the inner error for details.
------------------------------------------------
inner error: Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at Container.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:473:15)
    at Object.invoke (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:359:57)
    at InvocationHandler.invoke (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at StrategyResolver.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
    at Container.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:488:41)
    at r.configure (http://localhost:4000/jspm_packages/github/spoonx/aurelia-auth@master/index.js:13:41)
    at http://localhost:4000/jspm_packages/npm/aurelia-framework@1.0.0-beta.1.0.7/aurelia-framework.js:34:34
    at h (http://localhost:4000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66)
    at http://localhost:4000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
    at Container.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:473:15)
    at Object.invoke (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:359:57)
    at InvocationHandler.invoke (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at StrategyResolver.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
    at Container.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:488:41)
    at r.configure (http://localhost:4000/jspm_packages/github/spoonx/aurelia-auth@master/index.js:13:41)
    at http://localhost:4000/jspm_packages/npm/aurelia-framework@1.0.0-beta.1.0.7/aurelia-framework.js:34:34
    at h (http://localhost:4000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66)
    at http://localhost:4000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
    at new AggregateError (http://localhost:4000/jspm_packages/npm/aurelia-pal@1.0.0-beta.1.0.1/aurelia-pal.js:20:13)
    at Container.invoke (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:559:15)
    at StrategyResolver.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
    at Container.get (http://localhost:4000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:488:41)
    at r.configure (http://localhost:4000/jspm_packages/github/spoonx/aurelia-auth@master/index.js:13:41)
    at http://localhost:4000/jspm_packages/npm/aurelia-framework@1.0.0-beta.1.0.7/aurelia-framework.js:34:34
    at h (http://localhost:4000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66)
    at http://localhost:4000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
    at MutationObserver.e (http://localhost:4000/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1958:55)

**Comment by asdac** [comment]
same issue; https://github.com/paulvanbladel/aurelia-auth-sample/issues/10

**Comment by ghost** [comment]
Please ignore this was an issue with an older release
